name: CI

# run on the main branch, on tags, or on any pull request
on:
  push:
    branches: [main]
    tags: ["*"]
  pull_request:

jobs:

  # unit tests
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.10.4
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install -e .[tests]
    - name: Run unit tests
      run: |
        python -m unittest -v
