name: CI

# run on the main branch, on tags, or on any pull request
on:
  push:
    branches: [main]
    tags: ["*"]
  pull_request:

jobs:

  # unit tests
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.4
    - name: install dependencies
      run: |
        python -m pip install .[test]
    - name: run unit tests
      run: |
        python -m unittest -v
